### ISSUE TITLE
Format issues

### ISSUE THREAD

**Issue by QiLOL** [CJ42/All-About-Solidity-The-Book#1]
Hello, thanks for the book, there are several format issues may need to be fixed:

- Incomplete Links/content, for example:
  <img width="1132" alt="image" src="https://github.com/CJ42/All-About-Solidity-The-Book/assets/54246419/1f05cbbc-93fa-42e9-8840-58068d24bd8b">
  <img width="1194" alt="image" src="https://github.com/CJ42/All-About-Solidity-The-Book/assets/54246419/0326a14c-1aca-4942-889f-0ac3f193b405">
  <img width="1295" alt="image" src="https://github.com/CJ42/All-About-Solidity-The-Book/assets/54246419/26adfc99-f4be-4fd5-aa49-20063fb7fb2a">
  <img width="1217" alt="image" src="https://github.com/CJ42/All-About-Solidity-The-Book/assets/54246419/08855bc9-a127-4589-9c82-ce76d3f5f7ad">
  <img width="1157" alt="image" src="https://github.com/CJ42/All-About-Solidity-The-Book/assets/54246419/398ae24c-3113-417f-b3c2-256c7ab51e16">

- Link not usable: 
  <img width="1190" alt="image" src="https://github.com/CJ42/All-About-Solidity-The-Book/assets/54246419/b972620c-8f18-49b6-a916-63f43e561581">

- Some content looks weird, for example, not sure if it is the TODO items:
  <img width="1036" alt="image" src="https://github.com/CJ42/All-About-Solidity-The-Book/assets/54246419/f2e45d6f-ae20-4d1f-9ff9-0120572f33b2">

**Comment by CJ42** [comment]
@QiLOL thank you for your feedbacks! I have release v0.1.0-alpha.1 that should fix all these issues.
Marking this issue as complete ✅
